# Site settings
title: Hytale Server Container
description: A lightweight Dockerized environment for Hytale servers.
theme: jekyll-remote-theme
favicon_ico: "favicon.ico"

# Google Analytics settings
ga_tracking: G-L109Y1GVHR
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# Theme settings
remote_theme: just-the-docs/just-the-docs

# URL settings
baseurl: "" 
url: "https://hytale-server-container.com"
repository: deinfreu/hytale-server-container
permalink: pretty

# Aux links (Top right buttons)
aux_links:
  "GitHub":
    - "https://github.com/deinfreu/hytale-server-container"
  "Docker Hub":
    - "https://hub.docker.com/r/deinfreu/hytale-server" # Update if different

# Custoimization settings
callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: yellow
  info:
    title: Info
    color: blue
  note:
    title: Note
    color: purple

# Development settings
incremental: false  # Disable cache for reliable rebuilds
exclude:
  - README.md
  - .gitignore
  - dev/
  - Gemfile
  - Gemfile.lock