name: "ðŸš€ Publish: Release âž” Docker Hub & GitHub"

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  setup:
    name: "ðŸ—ï¸ Setup and Auth"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Verify Docker Hub Secrets
        run: |
          if [ -z "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then echo "Missing Username"; exit 1; fi
          if [ -z "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" ]; then echo "Missing Token"; exit 1; fi

  build:
    name: "ðŸ³ Build & Push Images"
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os_type: ubuntu
            dockerfile: Dockerfile.ubuntu
            tag_suffix: experimental
          - os_type: alpine
            dockerfile: Dockerfile.alpine
            tag_suffix: experimental-alpine
          - os_type: alpine-liberica
            dockerfile: Dockerfile.alpine-liberica
            tag_suffix: experimental-alpine-liberica
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version from tag
        id: get_version
        run: |
          raw_tag="${GITHUB_REF#refs/tags/}"
          version="${raw_tag#v}"
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Build & push to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/deinfreu/hytale-server:${{ matrix.tag_suffix }}-${{ steps.get_version.outputs.version }}
          cache-from: type=gha,scope=${{ matrix.tag_suffix }}-${{ steps.get_version.outputs.version }}
          cache-to: type=gha,mode=max,scope=${{ matrix.tag_suffix }}-${{ steps.get_version.outputs.version }}
      - name: Build & push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64
          tags: |
            deinfreu/hytale-server:${{ matrix.tag_suffix }}-${{ steps.get_version.outputs.version }}
          cache-from: type=gha,scope=${{ matrix.tag_suffix }}-${{ steps.get_version.outputs.version }}
          cache-to: type=gha,mode=max,scope=${{ matrix.tag_suffix }}-${{ steps.get_version.outputs.version }}