name: Experimental branch

on:
  push:
    branches:
      - experimental
  workflow_dispatch:

jobs:
  # 1. SETUP
  setup:
    name: üèóÔ∏è Setup and Auth
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  # 2. BUILD
  build:
    name: üê≥ Build & Push Multi-Arch
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: freudend/hytale-server:experimental
          build-args: |
            SERVER_JAR_URL=https://piston-data.mojang.com/v1/objects/64bb6d763bed0a9f1d632ec347938594144943ed/server.jar
            SERVER_JAR_SHA256=f83b8e093865806f931c7e34aae41b177d4c076335263dd124c75d6d65dd1726
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # 3. SCAN
  scan:
    name: üõ°Ô∏è Security Scan
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0 # Use a specific version for stability
        with:
          image-ref: 'freudend/hytale-server:experimental'
          format: 'table'
          exit-code: '0' 
          severity: 'CRITICAL,HIGH'